

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace trip_planer
{

    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Klasa częściowa <c>Trip_planerDBEntities : DbContext</c> zawiera metody 
    /// obsługujące elementy bazy danych.
    /// <list type="bullet">
    /// <item>
    /// <term>Trip_planerDBEntities </term>
    /// <description>Konstruktor klasy <c>Trip_planerDBEntities : DbContext</c>
    /// </description>
    /// </item>
    /// <item>
    /// <term>OnModelCreating </term>
    /// <description>Metoda wywoływana w chwili tworzenia modelu.</description>
    /// </item>
    /// </list>
    /// </summary>
    /// <remarks>
    /// <para> Klasa częściowa <c>Trip_planerDBEntities : DbContext</c> 
    /// zawiera metody obsługujące elementy bazę danych.</para>
    /// </remarks>
    public partial class Trip_planerDBEntities : DbContext
    {
        /// <summary>
        /// Konstruktor elementu bazy danych.
        /// </summary>
        /// <remarks>
        /// <para>Konstruktor elementu bazy danych.</para>
        /// </remarks>
        public Trip_planerDBEntities()
            : base("name=Trip_planerDBEntities")
        {

        }

        /// <summary>
        /// Metoda wywoływana w chwili tworzenia modelu..
        /// </summary>
        /// <remarks>
        /// <para>Metoda wywoływana w chwili tworzenia modelu..</para>
        /// </remarks>
        /// <exception cref="System.Exception">Wyrzucany, 
        /// gdy model zostanie stworzony.</exception>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <value>Kolekcja elementów tabeli <c>Ostatnie_tabela</c>.</value>
        public virtual DbSet<Ostatnie_tabela> Ostatnie_tabela { get; set; }

        /// <value>Kolekcja elementów tabeli <c>Ulubione_tabela</c>.</value>
        public virtual DbSet<Ulubione_tabela> Ulubione_tabela { get; set; }

    }

}

