
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace trip_planer
{

    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Klasa czêœciowa <c>Ulubione_tabela</c> zawiera w³aœciwoœci odpowiednie
    /// do odpowiedzi odpowiedniej czêœci aplikacji.
    /// </summary>
    /// <remarks>
    /// <para>Klasa czêœciowa <c>Ulubione_tabela</c> zawiera w³aœciwoœci odpowiednie
    /// do odpowiedzi odpowiedniej czêœci aplikacji.</para>
    /// </remarks>
    public partial class Ulubione_tabela
    {

        /// <value>Pobiera ID ostatniego elementu w tabeli <c>Ulubione_tabela</c>.</value>
        public int Id_ulubione { get; set; }

        /// <value>Pobiera nazwê miasta startowego w tabeli <c>Ulubione_tabela</c>.</value>
        public string poczatek_wycieczki { get; set; }

        /// <value>Pobiera nazwê miasta docelowego w tabeli <c>Ulubione_tabela</c>.</value>
        public string cel_wycieczki { get; set; }

        /// <value>Pobiera datê podró¿y w tabeli <c>Ulubione_tabela</c>.</value>
        public string data { get; set; }

    }

}
